name: Code analysis

env:
  NODE_VERSION: '22'

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  frontend_code_analysis:
    name: Frontend code analysis
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Validate audit
        run: npm audit --omit=dev

      - name: Validate build
        run: npm run build --if-present