name: Wedding app release

env:
  NODE_VERSION: '22'
  AZURE_STATIC_WEBAPP_NAME: 'swa-wedding-app'

on:
  release:
    types: [published]

jobs:
  build_frontend:
    name: Wedding app build
    runs-on: windows-2022
    env:
      NODE_VERSION: '22'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Include static web site config
        run: move staticwebapp.config.json build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_STATIC_WEBAPP_NAME }}
          path: dist

  deploy_frontend:
    name: Wedding app deloy
    runs-on: ubuntu-24.04
    needs: build_frontend

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_STATIC_WEBAPP_NAME }}

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEBAPP_UI_TOKEN_PRODUCTION }}
          action: "upload"
          app_location: "/"

      - name: Delete build artifact
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
            name: ${{ env.AZURE_STATIC_WEBAPP_NAME }}